apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: profile
  name: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: profile
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: profile
    spec:
      nodeName: node-1.qihang-winter0.ragger-pg0.utah.cloudlab.us
      containers:
        - command:
            - profile
          image: chenqh23/hotelreservation:latest
          name: hotel-reserv-profile
          ports:
            - containerPort: 8081
          resources:
            # requests:
            #   cpu: 100m
            limits:
              cpu: 3000m
      restartPolicy: Always
status: {}
